# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.srcs/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0.xci
# IP: The module: 'ADC1_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.gen/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC1_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.gen/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC1_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.srcs/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0.xci
# IP: The module: 'ADC1_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.gen/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC1_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.gen/sources_1/bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC1_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
