# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Vigtig_Constraint.xdc

# Block Designs: bd/ADC1/ADC1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC1 || ORIG_REF_NAME==ADC1} -quiet] -quiet

# IP: bd/ADC1/ip/ADC1_xadc_wiz_0_0/ADC1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC1_xadc_wiz_0_0 || ORIG_REF_NAME==ADC1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/ADC1/ip/ADC1_xlconstant_0_0/ADC1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC1_xlconstant_0_0 || ORIG_REF_NAME==ADC1_xlconstant_0_0} -quiet] -quiet

# IP: bd/ADC1/ip/ADC1_Shifter_0_0/ADC1_Shifter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC1_Shifter_0_0 || ORIG_REF_NAME==ADC1_Shifter_0_0} -quiet] -quiet

# XDC: c:/Users/axelo/OneDrive/Skrivebord/ADC_AXEL2/ADC_AXEL2.gen/sources_1/bd/ADC1/ADC1_ooc.xdc
